"""
Attack classifier using RandomForest trained on synthetic UNSW-NB15-like
network flow features.  Provides per-sample probability estimates over all
attack types, which the defender can incorporate into its state assessment.
"""

from __future__ import annotations

import os
from typing import Optional

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split

from attacker.attack_types import AttackType, FEATURE_NAMES
from attacker.attacker import Attacker


class AttackClassifier:
    """
    RandomForest classifier that maps raw network flow features to attack types.

    Designed to be trained on synthetic data generated by the Attacker's
    feature simulation, and then used in deployment to classify live
    (simulated) traffic.

    Parameters
    ----------
    n_estimators : int
        Number of trees in the forest.
    max_depth : int | None
        Maximum depth of each tree.
    random_state : int
        Seed for the classifier.
    n_jobs : int | None
        Number of jobs used by the underlying RandomForest. Defaults to
        serial execution to avoid joblib/scikit-learn parallel warnings on
        newer runtimes; set to -1 to use all cores.
    """

    def __init__(
        self,
        n_estimators:  int = 150,
        max_depth:     Optional[int] = 20,
        random_state:  int = 42,
        n_jobs:        Optional[int] = 1,
    ) -> None:
        self.model = RandomForestClassifier(
            n_estimators  = n_estimators,
            max_depth      = max_depth,
            random_state   = random_state,
            n_jobs         = n_jobs,
            class_weight   = "balanced",   # handle class imbalance
        )
        self.scaler        = StandardScaler()
        self.feature_names = list(FEATURE_NAMES)
        self.is_fitted     = False
        self._classes      = list(range(AttackType.count()))

    # ------------------------------------------------------------------
    # Data generation
    # ------------------------------------------------------------------

    def generate_training_data(
        self,
        n_samples_per_class: int = 600,
        seed: int = 42,
    ) -> tuple[pd.DataFrame, pd.Series]:
        """
        Generate labeled synthetic network flow data using the Attacker's
        feature simulation.

        Returns
        -------
        X : pd.DataFrame of shape (n_samples_per_class * n_classes, n_features)
        y : pd.Series of integer attack type labels
        """
        rows  = []
        labels = []

        for attack_type in AttackType:
            attacker = Attacker(seed=seed + int(attack_type))
            # Force the attacker to produce the desired attack type by
            # directly calling the feature simulator
            for _ in range(n_samples_per_class):
                features = attacker._simulate_features(attack_type)
                rows.append(features)
                labels.append(int(attack_type))

        X = pd.DataFrame(rows, columns=self.feature_names)
        y = pd.Series(labels, name="attack_type")
        return X, y

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------

    def fit(
        self,
        X: pd.DataFrame,
        y: pd.Series,
    ) -> "AttackClassifier":
        """Fit the scaler and RandomForest classifier. Returns self."""
        X_arr = X[self.feature_names].values.astype(np.float64)
        X_scaled = self.scaler.fit_transform(X_arr)
        self.model.fit(X_scaled, y.values)
        self.is_fitted = True
        return self

    def fit_from_simulation(
        self,
        n_samples_per_class: int = 600,
        seed: int = 42,
    ) -> "AttackClassifier":
        """Generate data and fit in one call."""
        X, y = self.generate_training_data(n_samples_per_class, seed)
        return self.fit(X, y)

    # ------------------------------------------------------------------
    # Inference
    # ------------------------------------------------------------------

    def predict(self, features: dict[str, float]) -> AttackType:
        """Classify a single sample given a feature dict."""
        self._check_fitted()
        arr = self._dict_to_array(features)
        pred = int(self.model.predict(arr)[0])
        return AttackType(pred)

    def predict_proba(self, features: dict[str, float]) -> np.ndarray:
        """
        Return probability estimates over all attack types for a single sample.

        Returns
        -------
        np.ndarray of shape (n_classes,) in AttackType order.
        """
        self._check_fitted()
        arr = self._dict_to_array(features)
        proba = self.model.predict_proba(arr)[0]
        # Ensure output covers all classes even if some were not in training
        full_proba = np.zeros(AttackType.count(), dtype=np.float64)
        for idx, cls in enumerate(self.model.classes_):
            full_proba[int(cls)] = proba[idx]
        return full_proba

    def predict_batch(self, X: pd.DataFrame) -> np.ndarray:
        """Batch prediction. Returns integer label array."""
        self._check_fitted()
        X_arr = X[self.feature_names].values.astype(np.float64)
        X_scaled = self.scaler.transform(X_arr)
        return self.model.predict(X_scaled)

    # ------------------------------------------------------------------
    # Evaluation
    # ------------------------------------------------------------------

    def evaluate(
        self,
        n_test_per_class: int = 200,
        seed: int = 99,
    ) -> dict:
        """
        Generate held-out test data, run prediction, and return metrics.

        Returns
        -------
        dict with keys: accuracy, report (full sklearn report dict)
        """
        X_test, y_test = self.generate_training_data(n_test_per_class, seed)
        y_pred = self.predict_batch(X_test)

        acc = accuracy_score(y_test, y_pred)
        report = classification_report(
            y_test, y_pred,
            target_names=AttackType.names(),
            output_dict=True,
        )
        return {"accuracy": acc, "report": report}

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def save(self, path: str) -> None:
        os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
        joblib.dump(
            {"model": self.model, "scaler": self.scaler, "feature_names": self.feature_names},
            path,
        )

    def load(self, path: str) -> "AttackClassifier":
        data = joblib.load(path)
        self.model         = data["model"]
        self.scaler        = data["scaler"]
        self.feature_names = data["feature_names"]
        self.is_fitted     = True
        return self

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _dict_to_array(self, features: dict[str, float]) -> np.ndarray:
        arr = np.array(
            [features.get(f, 0.0) for f in self.feature_names],
            dtype=np.float64,
        ).reshape(1, -1)
        return self.scaler.transform(arr)

    def _check_fitted(self) -> None:
        if not self.is_fitted:
            raise RuntimeError(
                "Classifier is not fitted. Call fit() or fit_from_simulation() first."
            )
